# Generated by Django 4.2.5 on 2023-09-21 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_member_debt_alter_transaction_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='stock_quantity',
        ),
    ]
