# Generated by Django 4.2.5 on 2023-09-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_book_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='ratings_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='text_reviews_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
